### ISSUE TITLE
Are permissions setup correctly?

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/remnote#9]
@justTOBBI and @coldenate have raised on discord that they are not able to close issues, do they have the correct permissions for this? 

Figured I'd raise the issue here for visibility instead of just on discord <3

**Comment by nekowinston** [comment]
I don't remember being pinged to add anyone as a maintainer to this repo, but I've just invited @coldenate as a maintainer.

**Comment by coldenate** [comment]
Thank you for working on this, @nekowinston! I'm a bit new to this type of OSS since I am usually on the PR side of things. If I were to make a change, should I make a PR or work on the direct branch? What would you recommend?  (*i'm going to paste this message into the thread on the discord since it may be a bit more conversational and appropriate on there*).

**Comment by nekowinston** [comment]
I'm personally only opening PRs if
 - they're needed to generate Changelogs
 - I want feedback from other people (e.g. have them try out a different branch)
 - if it's going to take a while to finish, and I want it to be visible that I'm working on it

As the org, we're pretty agnostic to how maintainers handle their repos. I think everyone's fine if you push directly to main.

Also closing this as completed since the maintainers are sorted out for now.

**Comment by coldenate** [comment]
Thank you! This comment helps!
